### ISSUE TITLE
Keep setting on reboot

### ISSUE THREAD

**Issue by arobass** [ViRb3/LenovoController#1]
Hello,

I'm using LenovoController 1.0.7 on Win10 1809, when I set the battery on "Conservative mode", it works  great on my Lenovo Legion5.

But If I reboot the setting is gone and I have to set it again on every boot.

Is it a normal behavior? How can I keep the setting or at least run the LenovoController with a script on boot to enforce my settings?

Thanks.

**Comment by ViRb3** [comment]
Hey,

Do you have Lenovo Vantage installed? It's probably reverting your settings, uninstall it. If you only have Lenovo Controller, your settings should persist.

**Comment by arobass** [comment]
I did install the Vantage "commercial". Will try to uninstall to see if settings are kept.

Strange since Vantage commercial doesn't have battery setting in ...

**Comment by arobass** [comment]
You were right, uninstalling the Vantage Commercial the setting is kept.

Nice work!

Thanks a lot!
