### ISSUE TITLE
Support Legion-5-Pro-16ACH6H

### ISSUE THREAD

**Issue by rshn-mrry** [ViRb3/LenovoController#10]
Hey there, I have a Legion-5-Pro-16ACH6H and would like to use this as a vantage alternative, what state is it in?

**Comment by ingmar** [comment]
Works fine on my Legion 7 16ACHg6, so probably okay on the 5 Pro which came out around the same time.

**Comment by ViRb3** [comment]
I'm assuming this was answered.
