### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by stupidpupil** [ViRb3/LenovoController#15]
Thank you again for this - not only is extremely helpful, but I've also found it extremely easy to build on, even as someone completely ignorant of almost everything involved.

With that in mind, would you be happy to stick on a licence on the repo? (Speaking entirely selfishly, I'd be glad of either MIT or GPLv3.)

**Comment by ViRb3** [comment]
Done, released under MIT :)

**Comment by stupidpupil** [comment]
Thanks!
