### ISSUE TITLE
Ideapad Gaming 3 15IMH05 crash in Windows 11 (22H2)

### ISSUE THREAD

**Issue by niizam** [ViRb3/LenovoController#19]
Windows version: 11 (22H2 OS Build 22621.232)

Steps to reproduce:
1. Download from release page
2. Extract the zip
3. Open `LenovoController.exe` with or without as Administrator
4. Result in the screenshot
![Screenshot 2022-09-11 061115](https://user-images.githubusercontent.com/45286708/189504792-1e6dcd43-479b-4295-ba9b-9758d889cff2.png)

**Comment by ViRb3** [comment]
What laptop is this? Note that only the Legion 7 2020 model is officially supported. I can confirm that LenovoController still works on this laptop and Windows 11 22H2.

**Comment by niizam** [comment]
> What laptop is this? Note that only the Legion 7 2020 model is officially supported. I can confirm that LenovoController still works on this laptop and Windows 11 22H2.

Sorry for waiting, it's Ideapad Gaming 3 15IMH05.

**Comment by ViRb3** [comment]
Ah. Unfortunately I do not own this device and I as such I can't fix the issue. I will remove it from the list of supported laptops in the README.

**Comment by niizam** [comment]
I reinstalled Windows and all its drivers, somehow it's working now.
![image](https://user-images.githubusercontent.com/45286708/194069859-69f88efe-0e7c-4aaa-b239-fca0176492e1.png)
