### ISSUE TITLE
Feature request - Performance mode enabled when games are running

### ISSUE THREAD

**Issue by ghost** [ViRb3/LenovoController#2]
There's an option in Lenovo Vantage to enable "Performance" mode only if games are running, and change back to whatever I was using upon exiting the game.
Is it possible to implement something similar on LenovoController? I assume your app would have to stay in background at all times, but this isn't much of an issue since ram usage of it is quite low.

**Comment by ViRb3** [comment]
I aim to keep this app as simple and minimal as possible. I don't want to clutter it with anything that's not hardware-specific. This feature sounds like something that could be done by another app. Perhaps I could export a command line interface that will allow you to switch between power modes programmatically. That way, you can integrate this app with any other app. I don't have the time to do this now, but I'll leave the issue open for the future.

**Comment by ViRb3** [comment]
Closing in favor of the issue above
