### ISSUE TITLE
how to compile for any lenovo laptop?

### ISSUE THREAD

**Issue by ghost** [ViRb3/LenovoController#22]
hey, your code is very helpful and much appreciated as it helps a lot for my ideapad s340, especially while playing xplane. i  would also like to have the other options like performance modes of touchpad lock options available, but instead of you compiling it for the laptop, can you teach me how to use my vantage driver to compile the source code of yours?

cheers.

**Comment by ViRb3** [comment]
This is sadly not possible. If the tool doesn't work for you as it is, it'll need changes specific for your laptop, which I cannot provide support for.

**Comment by ghost** [comment]
understood that, but can you give a briefing on what you do with the driver such as pass a command through the command with a true or false value
`echo "this_mode" true` or changing a specific value already running with the driver like `this_mode = true` ? (i am an absolute newbie, but would like to learn to suit to my needs). if not possible, its alright, the source code still works ok.

thanks

**Comment by ViRb3** [comment]
Unfortunately it's significantly more complicated than that - there is no command line for the driver and it's all magic bytes over the driver handle. The source is the best explanation I can offer at the moment. For anything else you'll need to reverse engineer built in software.

**Comment by ghost** [comment]
ah, sounds beyond my capabilities, thanks for the help anyway
