### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by BeastGorth** [ViRb3/LenovoController#26]
Hii.., i did hear about your program at reddit and want to try my self but i dont have any idea how to install this program ,as my self  dont have any experiance about coding before , any replay will be appreciated , thanks

**Comment by ViRb3** [comment]
No need to install, just download the ZIP file by clicking this link: https://github.com/ViRb3/LenovoController/releases/download/v1.0.7/LenovoController.zip

Then, extract it, and run the file that says `LenovoController.exe`.

That's all!

**Comment by BeastGorth** [comment]
looks like im downloaded the wrong zip file and it works on Y530 , thanks sir!
