### ISSUE TITLE
Energy driver error on Legion T5 28IMB05 and Thinkpad X1 Yoga (2nd gen)

### ISSUE THREAD

**Issue by CE1CECL** [ViRb3/LenovoController#4]
Hi there
This error keeps coming up on all app versions (since initial commit) and all windows versions (8.0 to 10)
I'm doing this on a Legion T5 28IMB05
Any help is appreciated
Thanks!

![Capture](https://user-images.githubusercontent.com/52040854/110216631-2401aa00-7e7e-11eb-8b1b-6f2309a727d8.png)

**Comment by SerpentDash** [comment]
Same error on my device: Thinkpad X1 Yoga (2nd gen)
Still anything we can do about this?

**Comment by ViRb3** [comment]
Seems like your models are missing, or have a different, energy driver:
https://github.com/ViRb3/LenovoController/blob/e3b4638bffeda239ff0c3486225460960c69122d/source/Providers/DriverProvider.cs#L18-L19

I can't help with support of a device that I do not own, unfortunately.

**Comment by SerpentDash** [comment]
Thanks for the reply. Could you tell what do you mean by 'energy driver'? Lenovo Energy Management?
What driver your device is using?
Maybe there is still a chance to find it somewhere and make it work (at least I could try)...

**Comment by ViRb3** [comment]
Each laptop with software, that can control hardware features like power profiles, will have a driver that makes it all work. In the Legion 7's case, this driver is the Energy Driver. If you find out how your laptop operates, and you submit a PR in this repo, I am more than happy to merge it.

**Comment by ingmar** [comment]
I just had the same issue. There was no EnergyDrv interface on my system. Looking into Device Manager I found an error on the "Lenovo ACPI-Compliant Virtual Power Controller", saying something about broken Registry settings. Possibly due to having had Vantage installed and then removing it.

The fix was to remove the device (select & DEL key), then re-detect hardware (button in toolbar) and let windows update the driver, after which the device reappeared without the error, the EnergyDrv interface showed up and LenovoController worked. Try that.

**Comment by CE1CECL** [comment]
![Capture](https://user-images.githubusercontent.com/52040854/135148846-5c226860-0dda-4bb9-87ac-6a3534071c8d.PNG)
![Capture](https://user-images.githubusercontent.com/52040854/135148862-168353e9-798b-42fe-a1cb-47916b44c88d.PNG)
This is for my machine

**Comment by CE1CECL** [comment]
> 
> 
> I just had the same issue. There was no EnergyDrv interface on my system. Looking into Device Manager I found an error on the "Lenovo ACPI-Compliant Virtual Power Controller", saying something about broken Registry settings. Possibly due to having had Vantage installed and then removing it.
> 
> The fix was to remove the device (select & DEL key), then re-detect hardware (button in toolbar) and let windows update the driver, after which the device reappeared without the error, the EnergyDrv interface showed up and LenovoController worked. Try that.

on what machine?

**Comment by SyedOmarNooredu** [comment]
same issue with x230 and both normal/commercial vantage

**Comment by CE1CECL** [comment]
Closing as my issue was partially solved, more info here: https://github.com/4JX/L5P-Keyboard-RGB/issues/61#issuecomment-1407493289
