### ISSUE TITLE
Feature request- Add Battery Gauge as panel

### ISSUE THREAD

**Issue by nik13513513** [ViRb3/LenovoController#5]
Hello, ViRb3!
Thanks for an app!

Can you add battery gauge to your app? For running app as windows panel like an Lenovo Vantage?

**Comment by ViRb3** [comment]
Can you please clarify what you mean by "Battery Gauge"? I've never used Vantage so I don't know what this is.

**Comment by nik13513513** [comment]
![изображение](https://user-images.githubusercontent.com/24268437/111023279-bd7e0e00-83e0-11eb-86c2-49b1ae6c1201.png)
I mean this panel

**Comment by ViRb3** [comment]
Oh, I see. Unfortunately, as I said in another feature request on this project:

> I aim to keep this app as simple and minimal as possible. I don't want to clutter it with anything that's not hardware-specific.

The battery gauge looks like something that could be done by another app. I don't aim to replicate Vantage, I just want to offer a way to control the hardware-specific features that are impossible in another way. If I start adding more and more features, this app will turn into Vantage itself. I hope you understand my reasoning.
